#!/bin/bash

echo -e "===\n>> Pre-push Hook: Checking branch name / Check branch..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
ALLOWED_BRANCHES="^(develop|feature/|bugfix/)"

if [[ $1 != *"$BRANCH"* ]]
then
  echo -e "\n🚫 You must use (git push origin $BRANCH) / Anda harus menggunakan (git push origin $BRANCH).\n" && exit 1
fi

if [[ ! "$BRANCH" =~ $ALLOWED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot push from branch $BRANCH. You are only allowed to push from branches starting with 'feature/' or 'bugfix/'."
  echo -e "🚫 Tidak bisa push dari branch $BRANCH. Anda hanya boleh push dari branch yang dimulai dengan 'feature/' atau 'bugfix/'.\n" && exit 1
fi

echo -e ">> Finish checking branch name / Selesai mengecek nama branch.\n==="

exit 0